config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  
  resource :session, only: [:new, :create, :destroy]
    
  resources :goals do
    resources :comments, only: [:create, :destroy]
  end
  
  root to: 'users#new'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  validates :body, :commentable_id, :commentable_type, :author_id, presence: true
  
  belongs_to(
    :commentable,
    polymorphic: true
  )
  
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :description, :user_id, :privacy, presence: true
  
  
  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many(
    :comments,
    :as => :commentable
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  has_many(
    :goals,
    class_name: 'Goal',
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
  :authored_comments,
  class_name: 'Comment',
  foreign_key: :author_id,
  primary_key: :id
  )
  
  has_many(
    :comments,
    :as => :commentable
  )
  
  def self.new_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(username, password)
    u = User.find_by(username: username)
    return u if u && u.has_password?(password)
    nil
  end
  
  def reset_session_token!
    self.session_token = self.class.new_session_token
    save!
  end
  
  def ensure_session_token
    self.session_token ||= self.class.new_session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def has_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  
  
  private
  attr_reader :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  protected 
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.authored_comments.new(comment_params)
    if @comment.save
      redirect_to :back
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
    
  end

  def destroy
  end
  
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      flash[:notices] = ['Goal saved successfully'] 
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
      
  end

  def destroy
    Goal.find(params[:id]).destroy!
  end
  
  def goal_params
    params.require(:goal).permit(:title, :description, :privacy, :completion)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new()
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    
    if @user
      # success
      login!(@user)
      flash[:notices] = [ "Successfully signed in!" ]
      redirect_to "/" # root_url
    else
      # failure
      flash.now[:errors] = [ "Invalid login!" ]
      render :new
    end
    
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @commentable_type = "User"
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      # success
      login!(@user)
      flash[:notices] = ["Successfully signed up!"]
      redirect_to "/" #root_url
    else
      # failure
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def auth_token
    "<input 
      type='hidden'
      name='authenticity_token'
      value= '#{form_authenticity_token}' >".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_form.html.erb
<% if @commentable_type == "Goal" %>
  <form action='<%= goal_comments_url(@comment) %>' method='post'>
    <input 
      type='hidden'
      name='comment[commentable_id]'
      value="<%= @goal.id %>"
      >
<% elsif @commentable_type == "User" %>
  <form action='<%= user_comments_url(@user) %>' method='post'>
    <input 
      type='hidden'
      name='comment[commentable_id]'
      value="<%= @user.id %>"
      >
<% end %>

  <%= auth_token %>
  
  <input 
    type='hidden'
    name='comment[commentable_type]'
    value="<%= @commentable_type %>"
    >

  <label for='comment_body'>Comment: </label>
  <input
    type='text'
    id='comment_body'
    name='comment[body]' %> 

  <input type='submit' value='Submit!'>
  
</form>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/goals/_form.html.erb
<% if @goal.persisted? %>
  <form action='<%= goal_url(@goal) %>' method='post'>
    <input
      type='hidden'
      name='_method'
      value='patch'>
<% else %>
  <form action='<%= goals_url %>' method='post'>
<% end %>
  <%= auth_token %>
  
  <label for='goal_title'>Title: </label>
  <input
    type='text'
    id='goal_title'
    name='goal[title]'
    value='<%= @goal.title %>'>
  
  <label for='goal_description'>Description: </label>
  <input
    type='text'
    id='goal_description'
    name='goal[description]'
    value='<%= @goal.description %>'>
    
  <label for='goal_privacy'>Privacy: </label>
  <input
    type='radio'
    id='goal_privacy'
    name='goal[privacy]'
    value="Private"
    <%= 'checked' if @goal.privacy == 'Private' %>
    >Private</input>
  <input
    type='radio'
    id='goal_privacy'
    name='goal[privacy]'
    value="Public"
    <%= 'checked' if @goal.privacy == 'Public' %>
    >Public</input>
  
  <label for='goal_completion'>Completion: </label>
  <select>
    <option value="new">New</option>
    <option value="in_progress">In Progress</option>
    <option value="complete">Complete</option>
  </select>
    
  <input type='submit' value='Submit!'>
  
</form>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<h1>Edit goal!</h1>
<p><%= render 'form'%></p>

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/goals/new.html.erb
<h1>Create a new goal!</h1>
<p><%= render 'form'%></p>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>
<%= @goal.description %>

<%= button_to('Edit Goal', edit_goal_url(@goal), method: :get ) %>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if current_user %>
  Hey there <%= current_user.username %>
  <%= button_to('Sign Out', session_url, method: :delete) %>
<% else %>
  <%= button_to('Sign In', new_session_url, method: :get) %>
  <%= button_to('Sign Up', new_user_url, method: :get) %>
<% end %>

<% flash.each do |type, msgs| %>
  <% msgs.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<form action='<%= users_url %>' method='post'>
  <%= auth_token %>
  
  <label for='user_username'>Username: </label>
  <input
    type='text'
    id='user_username'
    name='user[username]'
    value='<%= @user.username %>'>
  
  <label for='user_password'>Password: </label>
  <input
    type='password'
    id='user_password'
    name='user[password]'>
    
  <input type='submit' value='Submit!'>
  
</form>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Goals page for <%= @user.username %></h1>

<ul>
  <% @user.goals.each do |goal| %>
    <li> <%= link_to goal.title, goal_url(goal) %> </li>
  <% end%>
</ul>

<%= link_to "Create a new goal", new_goal_url %>


<%= render "comments/form" %>

<ul>
  <% @user.comments.each do |comment| %>
    <li> <%= comment.body %> </li>
  <% end%>
</ul>